local wk = require("which-key")

wk.add({
	{ "<leader>f", group = "Find" },
	{ "<leader>ff", desc = "Find File" },
	{ "<leader>fb", desc = "Find Buffer" },
	{ "<leader>fh", desc = "Find Help" },
	{ "<leader>fg", desc = "Find Text" },
	{ "<leader>e", desc = "File Manager" },
	{ "<leader>o", desc = "Git Status" },
	{ "<leader>x", desc = "Close Buffer" },
	{ "<leader>w", desc = "Save" },
	{ "<leader>t", group = "Terminal" },
	{ "<leader>tf", desc = "Float" },
	{ "<leader>th", desc = "Horizontal" },
	{ "<leader>tv", desc = "Vertical" },
	{ "<leader>h", desc = "No highlight" },
	{ "<leader>g", group = "Git" },
	{ "<leader>gb", desc = "Branches" },
	{ "<leader>gc", desc = "Commits" },
	{ "<leader>gs", desc = "Status" },
	{ "<leader>l", group = "LSP" },
	{ "<leader>ld", desc = "Diagnostic" },
	{ "<leader>lD", desc = "Hover diagnostic" },
	{ "<leader>lf", desc = "Format" },
	{ "<leader>lr", desc = "Rename" },
	{ "<leader>la", desc = "Action" },
	{ "<leader>ls", desc = "Symbol" },
})
